package com.pojo;
// Generated 25/07/2018 05:46:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private String identificacion;
     private String fechan;
     private String comunidad;
     private String acudiente;
     private String telefono;
     private Set alumnogrados = new HashSet(0);

    public Alumno() {
    }

    public Alumno(String nombre, String apellido, String identificacion, String fechan, String comunidad, String acudiente, String telefono, Set alumnogrados) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.identificacion = identificacion;
       this.fechan = fechan;
       this.comunidad = comunidad;
       this.acudiente = acudiente;
       this.telefono = telefono;
       this.alumnogrados = alumnogrados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getFechan() {
        return this.fechan;
    }
    
    public void setFechan(String fechan) {
        this.fechan = fechan;
    }
    public String getComunidad() {
        return this.comunidad;
    }
    
    public void setComunidad(String comunidad) {
        this.comunidad = comunidad;
    }
    public String getAcudiente() {
        return this.acudiente;
    }
    
    public void setAcudiente(String acudiente) {
        this.acudiente = acudiente;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getAlumnogrados() {
        return this.alumnogrados;
    }
    
    public void setAlumnogrados(Set alumnogrados) {
        this.alumnogrados = alumnogrados;
    }




}


