package com.pojo;
// Generated 12/01/2018 12:21:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumnogrado generated by hbm2java
 */
public class Alumnogrado  implements java.io.Serializable {


     private Integer id;
     private Alumno alumno;
     private Grado grado;
     private int ano;
     private Set notases = new HashSet(0);

    public Alumnogrado() {
    }

	
    public Alumnogrado(Alumno alumno, Grado grado, int ano) {
        this.alumno = alumno;
        this.grado = grado;
        this.ano = ano;
    }
    public Alumnogrado(Alumno alumno, Grado grado, int ano, Set notases) {
       this.alumno = alumno;
       this.grado = grado;
       this.ano = ano;
       this.notases = notases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }




}


