package com.pojo;
// Generated 25/07/2018 05:46:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materiaprofesor generated by hbm2java
 */
public class Materiaprofesor  implements java.io.Serializable {


     private Integer id;
     private Materia materia;
     private Profesor profesor;
     private String ano;
     private Set notases = new HashSet(0);

    public Materiaprofesor() {
    }

    public Materiaprofesor(Materia materia, Profesor profesor, String ano, Set notases) {
       this.materia = materia;
       this.profesor = profesor;
       this.ano = ano;
       this.notases = notases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }




}


