package com.pojo;
// Generated 12/01/2018 12:21:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set materiaprofesors = new HashSet(0);

    public Materia() {
    }

    public Materia(String nombre, Set materiaprofesors) {
       this.nombre = nombre;
       this.materiaprofesors = materiaprofesors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMateriaprofesors() {
        return this.materiaprofesors;
    }
    
    public void setMateriaprofesors(Set materiaprofesors) {
        this.materiaprofesors = materiaprofesors;
    }




}


