package com.pojo;
// Generated 25/07/2018 05:46:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notas generated by hbm2java
 */
public class Notas  implements java.io.Serializable {


     private Integer id;
     private Alumnogrado alumnogrado;
     private Materiaprofesor materiaprofesor;
     private String periodoi;
     private String periodoii;
     private String periodoiii;
     private String periodoiv;
     private String definitiva;
     private String ano;
     private String estado;
     private Date registro;

    public Notas() {
    }

	
    public Notas(Date registro) {
        this.registro = registro;
    }
    public Notas(Alumnogrado alumnogrado, Materiaprofesor materiaprofesor, String periodoi, String periodoii, String periodoiii, String periodoiv, String definitiva, String ano, String estado, Date registro) {
       this.alumnogrado = alumnogrado;
       this.materiaprofesor = materiaprofesor;
       this.periodoi = periodoi;
       this.periodoii = periodoii;
       this.periodoiii = periodoiii;
       this.periodoiv = periodoiv;
       this.definitiva = definitiva;
       this.ano = ano;
       this.estado = estado;
       this.registro = registro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alumnogrado getAlumnogrado() {
        return this.alumnogrado;
    }
    
    public void setAlumnogrado(Alumnogrado alumnogrado) {
        this.alumnogrado = alumnogrado;
    }
    public Materiaprofesor getMateriaprofesor() {
        return this.materiaprofesor;
    }
    
    public void setMateriaprofesor(Materiaprofesor materiaprofesor) {
        this.materiaprofesor = materiaprofesor;
    }
    public String getPeriodoi() {
        return this.periodoi;
    }
    
    public void setPeriodoi(String periodoi) {
        this.periodoi = periodoi;
    }
    public String getPeriodoii() {
        return this.periodoii;
    }
    
    public void setPeriodoii(String periodoii) {
        this.periodoii = periodoii;
    }
    public String getPeriodoiii() {
        return this.periodoiii;
    }
    
    public void setPeriodoiii(String periodoiii) {
        this.periodoiii = periodoiii;
    }
    public String getPeriodoiv() {
        return this.periodoiv;
    }
    
    public void setPeriodoiv(String periodoiv) {
        this.periodoiv = periodoiv;
    }
    public String getDefinitiva() {
        return this.definitiva;
    }
    
    public void setDefinitiva(String definitiva) {
        this.definitiva = definitiva;
    }
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Date registro) {
        this.registro = registro;
    }




}


