package com.pojo;
// Generated 12/01/2018 12:21:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private String fechan;
     private String departamento;
     private String ciudad;
     private String direccion;
     private String telefono;
     private String email;
     private Set materiaprofesors = new HashSet(0);

    public Profesor() {
    }

    public Profesor(String nombre, String apellido, String fechan, String departamento, String ciudad, String direccion, String telefono, String email, Set materiaprofesors) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechan = fechan;
       this.departamento = departamento;
       this.ciudad = ciudad;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.materiaprofesors = materiaprofesors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getFechan() {
        return this.fechan;
    }
    
    public void setFechan(String fechan) {
        this.fechan = fechan;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getMateriaprofesors() {
        return this.materiaprofesors;
    }
    
    public void setMateriaprofesors(Set materiaprofesors) {
        this.materiaprofesors = materiaprofesors;
    }




}


